### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by edumaciel10** [edumaciel10/lolo-game#2]
- [ ] relatório UML, comandos, instruções teclas etc
- [ ]  win game
- [ ]  Lógica ovos (https://github.com/edumaciel10/lolo-game/issues/24)
- [ ]  pegou a joia do bau mata todos os bixos
- [ ]  caveira correr atrás do bixo
- [ ]  tatuzao da 3
- [ ]  mexer os blocos -> depende do código do ovo
- [ ]  edu @edumaciel10

## Done
- [x] Ganhar tiros coração #22
- [x] edu #40
- [x] Edu #41

**Comment by edumaciel10** [comment]
## Done
- [x] #5
- [x] #3
- [x] #4
- [x] #11
- [x] #12
- [x] #15
- [x] #19
- [x] contabilizar mortes corretamente (https://github.com/edumaciel10/lolo-game/issues/16)
